### ISSUE TITLE
unique_episode calculated wrongly

### ISSUE THREAD

**Issue by eedlez** [aws-deepracer-community/deepracer-utils#26]
Hi,

due to a miscalculation of the episodes_per_worker_per_iteration (line 127 in logs/log.py), the unique_episode column gets wrong values. The code should look like (somehow I don't know how to format it better, sorry):

episodes_per_worker_per_iteration = df[(df["iteration"] == 0) & (df["worker"] == 0)]["episode"].max() **+ 1**
workers_count = df["worker"].max() + 1

df["unique_episode"] = df["episode"] + df["worker"] * episodes_per_worker_per_iteration + df["iteration"] * episodes_per_worker_per_iteration * workers_count

/Leon Zilverstand

**Comment by larsll** [comment]
https://github.com/aws-deepracer-community/deepracer-utils/blob/2414479c4f3073bc0ecdc94393f4a6fd1b51b3be/deepracer/logs/log.py#L127

**Comment by larsll** [comment]
@eedlez - we would be very happy to receive a pull request!

**Comment by eedlez** [comment]
Hi Lars, 
I would be glad to help on that, but I am not too familiar with the github process. If you can explain the process/steps to me (or guide me to a good explanation), I would be glad to add the code ;-). Btw, my solution proposed before is not yet 100% foolproof, so I'm still working on that, to make it even better ;-).
/Leon

**Comment by eedlez** [comment]
Hi Lars,
I created a pull request #28, I hope I did everything correctly, if not, please let me know how to do it better :-).
/Leon
