### ISSUE TITLE
Evaluation with multiple roboworkers doesn't function properly

### ISSUE THREAD

**Issue by eedlez** [aws-deepracer-community/deepracer-utils#27]
Hi,

as logs/log_utils.py uses episode column instead of unique_episode column, evaluation of logs with multiple workers is not working properly. I tried exchanging all references from episode to unique_episode and it works, both for single as well as multiple workers :-). Maybe this change could be incorporated in the official code as well :-).

Thanks,

Leon Zilverstand

**Comment by larsll** [comment]
@eedlez - we would be happy to receive pull requests with the relevant updates. :)

**Comment by larsll** [comment]
@eedlez - did this get resolved with #26 ?

**Comment by eedlez** [comment]
Hi Lars,

Partially, it took a while to get #26 done, which can be the base to fix this issue. Whenever I find some time I will have a look at it again.

/Leon

**Comment by eedlez** [comment]
Hi Lars,
@larsll , I just pushed the first part of a fix, which needs to be reviewed as I'm not 100% familiar with the code. The second part should be an update of the jupyter notebook to use unique_episode as well instead of episode.
/Leon

**Comment by larsll** [comment]
@eedlez - this should be fixed now; try it out in v1.0.0

**Comment by larsll** [comment]
No feedback. Closing.
